"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fontSizes = [14, 16, 20, 24, 32, 40, 48];
fontSizes.s = fontSizes[0];
fontSizes.n = fontSizes[1];
fontSizes.m = fontSizes[2];
fontSizes.l = fontSizes[3];
fontSizes.xl = fontSizes[4];
fontSizes['2xl'] = fontSizes[5];
fontSizes['3xl'] = fontSizes[6];
exports.default = fontSizes;
